export const ActionTypes = {

    //POPPER TABLE TYPES
    SET_USER_LOGIN: 'SET_USER_LOGIN',
    SET_USER_LOGIN_SUCCESS:"SET_USER_LOGIN_SUCCESS",
    SET_USER_LOGIN_FAILED:"SET_USER_LOGIN_FAILED",
    SET_USER_LOGIN_ERROR_MESSAGE:"SET_USER_LOGIN_ERROR_MESSAGE",
    CLEAN_LOGIN_ERROR_MESSAGE:"CLEAN_LOGIN_ERROR_MESSAGE",
    SET_USER_LOGOUT: 'SET_USER_LOGOUT',
    //theme switch
    SET_THEME_SWITCH: 'SET_THEME_SWITCH',
    //translation
    SET_TOPIC_LANGUAGE: 'SET_TOPIC_LANGUAGE',
}